# package installation via this file is being replaced by ../nix/pkgs.nix
# this may be used as an fallback

# essential
brew "coreutils" # https://formulae.brew.sh/formula/coreutils
brew "zsh" # my favorite shell interface
brew "git" # to replace possible old git comes with OS
brew "bash" # use latest bash
brew "tmux" # terminal multiplexer
brew "neovim" # my favorite editor
brew "starship" # cross-shell prompt
brew "fzf" # A command-line fuzzy finder
brew "direnv" # auto loading env per dir
brew "htop" # resource monitoring
brew "gpg" # GnuPG
brew "wget" # useful for downloading files
brew "iproute2mac" # ip command
brew "emacs" # due to the issue mentioned at https://discourse.nixos.org/t/is-it-currently-possible-to-use-emacs-on-aarch64-darwin/31571
brew "syncthing" # Open Source Continuous File Synchronization

# viewer
brew "eza" # modern ls
brew "bat" # cat with wings
brew "glow" # markdown render on cli
brew "lf" # terminal file manager
brew "fx" # json viewer
brew "hexyl" # binary viewer

# search
brew "rg" # modern grep
brew "zoxide" # Command-line productivity booster, offers quick access to files and directories
brew "fd" # mordern find

# helper
brew "tig" # git helper
brew "tldr" # Simplified and community-driven man pages
brew "watch" # execute a program periodically
brew "entr" # Run arbitrary commands when files change
brew "taskell" # CLI kanban
brew "fpp" # for tmux-fpp
brew "extract_url" # for tmux-urlview
brew "jq" # json processor
brew "jsonnet" # templating with json
brew "gh" # official Github CLI
brew "pueue" # long running task manager

# misc
brew "neofetch"
brew "yarn"

# not core tap
brew "kdabir/tap/has"
