## basics

# terminal and editor
export TERM="xterm-256color"
export EDITOR=nvim

# vi keybinding
export KEYTIMEOUT=1
bindkey -v

# enable reverse-i-search
bindkey '^R' history-incremental-search-backward

## addons

# source from seperate files to organize better
export ADDON_D=~/.config/zshrc.d/my_addons
for source_file in omz zinit lf_icons aliases shell_ext
do 
[ -f $ADDON_D/$source_file ] && source $ADDON_D/$source_file
done
unset ADDON_D
