# https://starship.rs/config

# https://starship.rs/config/#shell
[shell]
disabled = false

# https://starship.rs/config/#shlvl
[shlvl]
disabled = false
threshold = 3

# https://starship.rs/config/#battery-display
[[battery.display]]
threshold = 80
style = "yellow"

# https://starship.rs/config/#git-branch
[git_branch]
symbol = "🌱 "

# https://starship.rs/config/#git-status
[git_status]
conflicted = "🏳"
ahead = "🏎💨${count}"
behind = "🐢${count}"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\(${count}\)](green)'
renamed = "👅"
deleted = "🗑"

# https://starship.rs/config/#kubernetes
[kubernetes]
symbol = "⛴  "
style = "dimmed green"
disabled = false

# https://starship.rs/config/#terraform
[terraform]

# https://starship.rs/config/#nix-shell
[nix_shell]

# https://starship.rs/config/#aws
[aws]
symbol = '🅰 '

# Show the tmux session name if the $TMUX environment variable is set
[custom.tmux]
# Targets the specific pane to avoid "ghosting" via TMUX_PANE
command = """
tmux display-message -t "$TMUX_PANE" -p '#S:#{session_windows}:#I:#{window_panes}:#P' | awk -F: '{
  session=$1; win_count=$2; win_idx=$3; pane_count=$4; pane_idx=$5;

  printf session;
  if (win_count > 1 || pane_count > 1) printf ":" win_idx;
  if (pane_count > 1) printf "." pane_idx;
}'
"""
when = 'test -n "$TMUX" && test -n "$TMUX_PANE"'
format = 'at [ $output]($style) '
style = 'bold blue'
