# --search-parent-directories is a default arg for null_ls.builtins.formatting.stylua
# so that formatting lua file will look for this file
# according to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/15d3aabc2b440293ecf6c85f25ca9fa645a468ae/lua/null-ls/builtins/formatting/stylua.lua#L14

indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
