#!/usr/bin/env bash

curr_dir="$(dirname "$0")"
pushd "${curr_dir}"

mix_and_match=$(test -f ../../../nix/nixos/mix-and-match.nix && echo ../../../nix/nixos/mix-and-match.nix)

cat << EOF > ./configuration.nix
# generated by ./gen-configuration.sh

# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

let
  my-nixos = ../../../nix/nixos/configuration.nix;
  user = import ../../../nix/nixos/user.nix {
    username = "$(whoami)";
  };
in
{
  imports =
    [
      # Include the results of the hardware scan.
      my-nixos
      ${mix_and_match}
      user
    ];
}
EOF
