#!/usr/bin/env bash

curr_dir="$(dirname "$0")"
cd "${curr_dir}" || exit

mix_and_match=$(test -f ../../../nix/nixos/mix-and-match.nix && echo ../../../nix/nixos/mix-and-match.nix)

cat <<EOF >./configuration.nix
# generated by ./gen-configuration.sh

# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

let
  my-nixos = ../../../nix/nixos/configuration.nix;
  username = "$(whoami)";
  user = import ../../../nix/nixos/user.nix {
    username = username;
  };
  mix-and-match = import ${mix_and_match} username;
in
{
  imports =
    [
      # Include the results of the hardware scan.
      my-nixos
      user
      mix-and-match
    ];
}
EOF
