.PHONY: default
default: show help update-indivisual

.PHONY: help
help:
	niv --help

.PHONY: show
show:
	niv show

.PHONY: update-indivisual
update-indivisual:
	@echo; echo 'run `niv update [repo]` to update individual repo'; echo

.PHONY: update-all
update-all:
	niv update
