#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "curve"
    statusline_inactive_separator = "curve"
    statusline_unicode_symbols = false

    # font or shape of buffer number
    buffer_index_type = 2 
    # font or shape of window number
    windows_index_type = 3
    enable_tabline_filetype_icon = true

    # filetree
    filetree_direction = "right"
    filemanager = "defx"

    # load vim custom setup
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'git'
git-plugin = 'fugitive'

[[layers]]
name = "denite"

[[custom_plugins]]
name = "zxqfl/tabnine-vim"
merged = false
[[custom_plugins]]
name = "ryanoasis/vim-devicons"
merged = false
[[custom_plugins]]
name = "tpope/vim-surround"
merged = false
[[custom_plugins]]
name = "vim-scripts/ReplaceWithRegister"
merged = false
[[custom_plugins]]
name = "christoomey/vim-titlecase"
merged = false
[[custom_plugins]]
name = "christoomey/vim-system-copy"
merged = false
[[custom_plugins]]
name = "tpope/vim-commentary"
merged = false
[[custom_plugins]]
name = "hashivim/vim-terraform"
merged = false
[[custom_plugins]]
name = "christoomey/vim-tmux-navigator"
merged = false
[[custom_plugins]]
name = "tmux-plugins/vim-tmux-focus-events"
merged = false
[[custom_plugins]]
name = "benmills/vimux"
merged = false
[[custom_plugins]]
name = "junegunn/goyo.vim"
merged = false
[[custom_plugins]]
name = "junegunn/limelight.vim"
merged = false
[[custom_plugins]]
name = "kristijanhusak/defx-git"
merged = false
[[custom_plugins]]
name = "kristijanhusak/defx-icons"
merged = false
[[custom_plugins]]
name = "tmux-plugins/vim-tmux-focus-events"
merged = 0
[[custom_plugins]]
name = "roxma/vim-tmux-clipboard"
merged = 0
