#!/usr/bin/env bash

curr_dir="$(dirname "$0")"
cd "${curr_dir}" || exit

cat <<EOF >./configuration.nix
# generated by ./gen-configuration.sh

# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

let
  username = "$(whoami)";
  with-primary-user = import ./meta-configuration.nix { username = username; };
in
{
  imports =
    [
      with-primary-user
    ];
}
EOF
